<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\De4DotCommon.props" />

  <PropertyGroup>
    <BaseOutputPath>E:\Crack\0.Tools\de4dot</BaseOutputPath>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\dnlib\src\dnlib.csproj" />
  </ItemGroup>

</Project>
